#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, os.path
src = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src')
sys.path.insert(0, src)
from Tardis import Client

sys.exit(Client.main())
